<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CarRentalGridForm.BL.Contracts\CarRentalGridForm.BL.Contracts.csproj" />
    <ProjectReference Include="..\CarRentalGridForm.BL\CarRentalGridForm.BL.csproj" />
    <ProjectReference Include="..\CarRentalGridForm.Constants\CarRentalGridForm.Constants.csproj" />
    <ProjectReference Include="..\CarRentalGridForm.DAL\CarRentalGridForm.DAL.csproj" />
    <ProjectReference Include="..\CarRentalGridForm.Helpers\CarRentalGridForm.Helpers.csproj" />
    <PackageReference Include="CarRentalGridForm.Models" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CarEditForm.cs" />
    <Compile Update="MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>