<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>CarRentalGridForm.Web</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CarRentalGridForm.BL\CarRentalGridForm.BL.csproj" />
      <ProjectReference Include="..\CarRentalGridForm.DAL\CarRentalGridForm.DAL.csproj" />
    </ItemGroup>

</Project>
